// apps/web/src/routes/login/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { type AuthFailReason, authFailReason } from "$lib/login";

  $: {
    const ticket = $page.url.searchParams.get("ticket");

    if (ticket && typeof document !== "undefined") {
      const ticketInput = document.getElementById("ticket") as HTMLInputElement;
      ticketInput.value = ticket;
    }
  }

  $: errorCode = $page.url.searchParams.get("error");
  $: errorMsg = errorCode
    ? authFailReason[errorCode as AuthFailReason] || "Unknown Error"
    : null;
</script>

<main
  class="flex h-screen flex-col items-center justify-center gap-8 bg-gray-100"
>
  {#if errorMsg}
    <p class="text-lg font-medium text-red-500">{errorMsg}</p>
  {/if}

  <form
    class="flex w-full max-w-lg flex-col gap-4 rounded-lg bg-white p-6 shadow-md"
    method="POST"
  >
    <div>
      <label class="mb-2 block font-bold text-gray-700" for="ticket">
        Ticket
      </label>
      <input
        class="focus:shadow-outline w-full rounded border px-3 py-2 leading-tight text-gray-700 shadow focus:outline-none"
        name="ticket"
        id="ticket"
        type="text"
        placeholder="/login to get your ticket"
        required
      />
    </div>
    <div class="flex items-center justify-between">
      <button
        class="focus:shadow-outline rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700 focus:outline-none"
        type="submit"
      >
        Login
      </button>
    </div>
  </form>
</main>

// apps/client/src/pages/login.tsx
import { useContext, useEffect, useState } from "react";

import { NextPage } from "next";
import { useRouter } from "next/router";

import { AuthContext } from "$lib/contexts";

const LoginPage: NextPage = () => {
  const router = useRouter();

  const { login } = useContext(AuthContext);

  const [token, setToken] = useState("");

  useEffect(() => {
    const queryToken =
      typeof router.query.token === "string"
        ? router.query.token
        : router.query.token?.[0];

    setToken(queryToken ?? localStorage.getItem("token") ?? "");
  }, [router.query.token]);

  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-2">
      <h1 className="page-title">Login</h1>

      <label className="text-4xl" htmlFor="token">
        Enter your access token
      </label>
      <input
        className="m-4 h-12 w-2/3 rounded-lg border border-black bg-neutral-200 p-2"
        name="token"
        type="text"
        value={token}
        onChange={(e) => setToken(e.currentTarget.value)}
      />

      <button
        className="rounded-xl bg-gradient-to-br from-pink-200 to-pink-300 p-4 text-3xl font-bold disabled:from-gray-300 disabled:to-neutral-400"
        disabled={token.length < 10}
        onClick={() => login(token ?? "")}
      >
        Set Token
      </button>
    </main>
  );
};

export default LoginPage;
